"""use enum for delivery status

Revision ID: 17157da706bb
Revises: ff2c80287576
Create Date: 2022-03-29 22:30:33.608238

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '17157da706bb'
down_revision = 'ff2c80287576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE deliverystatus as ENUM ('created', 'in_progress', 'finished')"
    )
    op.execute(
        'ALTER TABLE delivery_deliveries ALTER COLUMN status TYPE deliverystatus USING status::deliverystatus'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_deliveries', 'status',
                    existing_type=sa.Enum(
                        'created', 'in_progress', 'finished', name='deliverystatus'),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    # ### end Alembic commands ###
