"""add created and updated at

Revision ID: 226aff7857c1
Revises: 7f34c4ff4cce
Create Date: 2022-05-02 20:21:48.121790

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '226aff7857c1'
down_revision = '7f34c4ff4cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_addresses', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_addresses', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_deliverers', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_deliverers', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_deliveries', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_deliveries', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_delivery_route_addresses', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_delivery_route_addresses', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_delivery_routes', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_delivery_routes', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_order_problems', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_order_problems', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_order_products', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_order_products', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_orders', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_orders', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_suppliers', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_suppliers', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE delivery_addresses set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_addresses set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_deliverers set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_deliverers set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_deliveries set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_deliveries set updated_at = '2022-05-02'")
    op.execute(
        "UPDATE delivery_delivery_route_addresses set created_at = '2022-05-02'")
    op.execute(
        "UPDATE delivery_delivery_route_addresses set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_delivery_routes set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_delivery_routes set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_order_problems set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_order_problems set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_order_products set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_order_products set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_orders set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_orders set updated_at = '2022-05-02'")
    op.execute("UPDATE delivery_suppliers set created_at = '2022-05-02'")
    op.execute("UPDATE delivery_suppliers set updated_at = '2022-05-02'")
    op.alter_column('delivery_addresses', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_addresses', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_deliverers', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_deliverers', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_deliveries', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_deliveries', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_delivery_route_addresses', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_delivery_route_addresses', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_delivery_routes', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_delivery_routes', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_order_problems', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_order_problems', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_order_products', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_order_products', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_orders', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_orders', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_suppliers', sa.Column(
        'created_at', sa.DateTime(), nullable=False))
    op.alter_column('delivery_suppliers', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_suppliers', 'updated_at')
    op.drop_column('delivery_suppliers', 'created_at')
    op.drop_column('delivery_orders', 'updated_at')
    op.drop_column('delivery_orders', 'created_at')
    op.drop_column('delivery_order_products', 'updated_at')
    op.drop_column('delivery_order_products', 'created_at')
    op.drop_column('delivery_order_problems', 'updated_at')
    op.drop_column('delivery_order_problems', 'created_at')
    op.drop_column('delivery_delivery_routes', 'updated_at')
    op.drop_column('delivery_delivery_routes', 'created_at')
    op.drop_column('delivery_delivery_route_addresses', 'updated_at')
    op.drop_column('delivery_delivery_route_addresses', 'created_at')
    op.drop_column('delivery_deliveries', 'updated_at')
    op.drop_column('delivery_deliveries', 'created_at')
    op.drop_column('delivery_deliverers', 'updated_at')
    op.drop_column('delivery_deliverers', 'created_at')
    op.drop_column('delivery_addresses', 'updated_at')
    op.drop_column('delivery_addresses', 'created_at')
    # ### end Alembic commands ###
