"""add cascade to order problem

Revision ID: 7f34c4ff4cce
Revises: e60db3f64166
Create Date: 2022-04-23 17:29:08.782846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f34c4ff4cce'
down_revision = 'e60db3f64166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delivery_order_problems_order_id_fkey', 'delivery_order_problems', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_order_problems', 'delivery_orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_order_problems', type_='foreignkey')
    op.create_foreign_key('delivery_order_problems_order_id_fkey', 'delivery_order_problems', 'delivery_orders', ['order_id'], ['order_id'])
    # ### end Alembic commands ###
