"""add delivery date and name

Revision ID: 9725f4897aeb
Revises: a404e62d855e
Create Date: 2022-03-14 09:03:22.109739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9725f4897aeb'
down_revision = 'a404e62d855e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_deliveries', sa.Column(
        'delivery_date', sa.DateTime(), nullable=True))
    op.execute('UPDATE delivery_deliveries SET delivery_date = NOW()')
    op.alter_column('delivery_deliveries', 'delivery_date', nullable=False)
    op.add_column('delivery_deliveries', sa.Column(
        'name', sa.String(length=255), nullable=True))
    op.execute("UPDATE delivery_deliveries SET name = 'a'")
    op.alter_column('delivery_deliveries', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_deliveries', 'name')
    op.drop_column('delivery_deliveries', 'delivery_date')
    # ### end Alembic commands ###
