"""add cascade on delete

Revision ID: e60db3f64166
Revises: 17157da706bb
Create Date: 2022-04-23 16:20:18.731670

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e60db3f64166'
down_revision = '17157da706bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('delivery_deliverers_delivery_id_fkey',
                       'delivery_deliverers', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_deliverers', 'delivery_deliveries', [
                          'delivery_id'], ['delivery_id'], ondelete='CASCADE')
    op.drop_constraint('delivery_delivery_route_addresses_delivery_route_id_fkey',
                       'delivery_delivery_route_addresses', type_='foreignkey')
    op.drop_constraint('delivery_delivery_route_addresses_address_id_fkey',
                       'delivery_delivery_route_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_delivery_route_addresses', 'delivery_addresses', [
                          'address_id'], ['address_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'delivery_delivery_route_addresses', 'delivery_delivery_routes', [
                          'delivery_route_id'], ['delivery_route_id'], ondelete='CASCADE')
    op.drop_constraint('delivery_delivery_routes_delivery_id_fkey',
                       'delivery_delivery_routes', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_delivery_routes', 'delivery_deliveries', [
                          'delivery_id'], ['delivery_id'], ondelete='CASCADE')
    op.drop_constraint('delivery_order_products_order_id_fkey',
                       'delivery_order_products', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_order_products', 'delivery_orders', [
                          'order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint('delivery_orders_delivery_id_fkey',
                       'delivery_orders', type_='foreignkey')
    op.drop_constraint('delivery_orders_shipping_address_id_fkey',
                       'delivery_orders', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_orders', 'delivery_deliveries', [
                          'delivery_id'], ['delivery_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'delivery_orders', 'delivery_addresses', [
                          'shipping_address_id'], ['address_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.create_foreign_key('delivery_orders_shipping_address_id_fkey', 'delivery_orders',
                          'delivery_addresses', ['shipping_address_id'], ['address_id'])
    op.create_foreign_key('delivery_orders_delivery_id_fkey', 'delivery_orders',
                          'delivery_deliveries', ['delivery_id'], ['delivery_id'])
    op.drop_constraint(None, 'delivery_order_products', type_='foreignkey')
    op.create_foreign_key('delivery_order_products_order_id_fkey',
                          'delivery_order_products', 'delivery_orders', ['order_id'], ['order_id'])
    op.drop_constraint(None, 'delivery_delivery_routes', type_='foreignkey')
    op.create_foreign_key('delivery_delivery_routes_delivery_id_fkey',
                          'delivery_delivery_routes', 'delivery_deliveries', ['delivery_id'], ['delivery_id'])
    op.drop_constraint(
        None, 'delivery_delivery_route_addresses', type_='foreignkey')
    op.drop_constraint(
        None, 'delivery_delivery_route_addresses', type_='foreignkey')
    op.create_foreign_key('delivery_delivery_route_addresses_address_id_fkey',
                          'delivery_delivery_route_addresses', 'delivery_addresses', ['address_id'], ['address_id'])
    op.create_foreign_key('delivery_delivery_route_addresses_delivery_route_id_fkey',
                          'delivery_delivery_route_addresses', 'delivery_delivery_routes', ['delivery_route_id'], ['delivery_route_id'])
    op.drop_constraint(None, 'delivery_deliverers', type_='foreignkey')
    op.create_foreign_key('delivery_deliverers_delivery_id_fkey', 'delivery_deliverers',
                          'delivery_deliveries', ['delivery_id'], ['delivery_id'])
    # ### end Alembic commands ###
