name: delivery_manager
version: 1.0.0+1
publish_to: none
description: Delivery Manager Mobile App
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: 4.3.8
  cupertino_icons: ^1.0.2
  http: 0.13.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

