name: delivery_manager
version: 1.0.0+1
publish_to: none
description: Delivery Manager Mobile App
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.2
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^1.1.0
  get: ^4.3.8
  http: ^0.13.4
  mask_text_input_formatter: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_screenutil: ^5.1.1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  get_cli: ^1.7.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.1.4
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  fonts:
    - family: "GeneralSans"
      fonts:
        - asset: "assets/fonts/GeneralSans-Extralight.otf"
          weight: 200
        - asset: "assets/fonts/GeneralSans-ExtralightItalic.otf"
          weight: 200
          style: italic
        - asset: "assets/fonts/GeneralSans-Light.otf"
          weight: 300
        - asset: "assets/fonts/GeneralSans-LightItalic.otf"
          weight: 300
          style: italic
        - asset: "assets/fonts/GeneralSans-Regular.otf"
          weight: 400
        - asset: "assets/fonts/GeneralSans-Italic.otf"
          weight: 400
          style: italic
        - asset: "assets/fonts/GeneralSans-Medium.otf"
          weight: 500
        - asset: "assets/fonts/GeneralSans-MediumItalic.otf"
          weight: 500
          style: italic
        - asset: "assets/fonts/GeneralSans-Semibold.otf"
          weight: 600
        - asset: "assets/fonts/GeneralSans-SemiboldItalic.otf"
          weight: 600
          style: italic
        - asset: "assets/fonts/GeneralSans-Bold.otf"
          weight: 700
        - asset: "assets/fonts/GeneralSans-BoldItalic.otf"
          weight: 700
          style: italic
  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/launcher_icon.png
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/images/splash.png"
