name: Delivery API Deployment

on: [push]

jobs:
  deploy_api:
    defaults:
      run:
        working-directory: Codigo/DeliveryApi
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      DB_SERVER_URL: ${{secrets.DB_SERVER_URL}}
      MQ_EXCHANGE: ${{secrets.MQ_EXCHANGE}}
      MQ_URL: ${{secrets.MQ_URL}}
      FLASK_ENV: production
      FLASK_APP: main.py

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}

      - name: Setup virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run linter
        env:
          FLASK_ENV: testing
        run: |
          . venv/bin/activate
          pylint src

      - name: Run tests
        env:
          FLASK_ENV: testing
        run: |
          . venv/bin/activate
          coverage run
          coverage report

      - name: Login to heroku
        if: contains(github.ref, 'master')
        run: heroku container:login

      - name: Build and Push
        if: contains(github.ref, 'master')
        run: heroku container:push -a trela-delivery-api web

      - name: Release
        if: contains(github.ref, 'master')
        run: heroku container:release -a trela-delivery-api web
