name: New Students Api Pipeline

on: [push]

jobs:
  deploy_api:
    defaults:
      run:
        working-directory: Codigo/DeliveryApi

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Setup virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run linter
        run: |
          . venv/bin/activate
          pylint src

      - name: Run tests
        run: |
          . venv/bin/activate
          coverage run
          coverage report

      - name: Login to heroku
        if: contains(github.ref, 'master')
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

      - name: Build and Push
        if: contains(github.ref, 'master')
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:push -a trela-delivery-api web

      - name: Release
        if: contains(github.ref, 'master')
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release -a trela-delivery-api web
