name: Mobile App Integration Tests

on:
  push:
    branches:
      - master

jobs:
  integration_tests:
    defaults:
      run:
        working-directory: Codigo/MobileApp

    env:
      API_URL: ${{secrets.API_URL}}
      MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0
          channel: stable
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: List all simulators
        run: xcrun simctl list

      - name: Start Simulator
        run: open -a Simulator.app

      - name: Install dependencies
        run: |
          flutter pub get
          touch .env
          echo "API_URL=$API_URL" > .env
          flutter pub run build_runner build

      - name: Run tests
        run: |
          cat .env
          flutter test integration_test
