name: Mobile App Pipeline

on:
  push:
    paths:
      - Codigo/MobileApp/**/*
      - .github/workflows/mobile_pipe.yml

jobs:
  mobile_pipe:
    defaults:
      run:
        working-directory: Codigo/MobileApp
    env:
      API_URL: ${{secrets.API_URL}}

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0
          channel: stable
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          touch assets/.env
          echo "API_URL={{secrets.API_URL}}" > assets/.env
          flutter pub run build_runner build

      - name: Run analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build android
        if: github.ref == 'ref/head/master'
        run: flutter build appbundle --release

      - name: Build IOS
        if: github.ref == 'ref/head/master'
        run: flutter build ios --release --no-codesign

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: |
            build/**/outputs/bundle/**/*.aab
            build/ios/ipa/*.ipa
            /tmp/xcodebuild_logs/*.log
